### ISSUE TITLE
[docs]: Add example of how to add your own snippets to a pattern

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3824] opened 2023-04-15 18:02 UTC
### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

**Comment by BenJamesBen** [comment] 2023-04-19 01:48
For examples, see: https://github.com/freesewing/freesewing/pull/3489

**Comment by SeaZeeZee** [comment] 2023-05-18 08:42
I'm looking at where to add this and now Im wondering, does this page already cover this issue? https://v2-freesewing-36oo7084u-freesewing.vercel.app/howtos/code/adding-snippets

I can absolutely write a different example if necessary but I'm a bit too brainfogged to figure out if the issue is resolved by the page above.

**Comment by BenJamesBen** [comment] 2023-05-18 20:37
The existing documentation covers "how to add existing snippets to a pattern". As I understand it, this docs enhancement request is for "how to create new, not-yet-existent snippets and add them to a pattern".

**Closed** 2023-10-30 18:00 UTC
Labels: :book: documentation
