### ISSUE TITLE
[docs]: Add sharp rebuild instructions to dev documentation

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3979] opened 2023-05-04 03:57 UTC
### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

This is important information that should be documented. However, I am not sure where to add it. There doesn't seem to be a natural place it should go in the current dev documentation structure. We might want to consider reorganizing the dev documentation structure, but for now I am filing this bug to save the information and track the issue.

### Additional context

Possible wording (written assuming it would go into a Frequently Asked Questions section):

---
title: Someting went wrong installing the "sharp" module
---

## The problem

When trying to run the `yarn lab` development environment after
updating your workspace, you get a
`Something went wrong installing the "sharp" module` error.

For example:
```sh
% yarn lab
...

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
Require stack:
- /.../freesewing/node_modules/sharp/lib/sharp.js
- /.../freesewing/node_modules/sharp/lib/constructor.js
- /.../freesewing/node_modules/sharp/lib/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
.
```

## The Solution

Run the `npm rebuild sharp` command.

```sh
% npm rebuild sharp
rebuilt dependencies successfully
%
```

## Explanation

`sharp` is a JavaScript package that needs to compile local, native
language bindings on install.
Those bindings are platform specific, and it is not uncommon for the
compilation attempt to be unsuccessful during the initial `yarn kickstart`
process.

The `npm rebuild sharp` command forces a rebuild of the language bindings
to fix the issue.

Because `sharp` tends to cause these issues for people, FreeSewing is
trying to eliminate its use in our repository.
However, for now it is still a dev dependency needed to generate open
graph images.

**Comment by joostdecock** [comment] 2023-05-11 13:49
Closing as this is de-facto a dupe of #3066

**Closed by joostdecock** 2023-05-11 13:49 UTC
Labels: :book: documentation, :+1: good first issue
