### ISSUE TITLE
[bug]: Unable to use advanced options in Teagan

### ISSUE THREAD

**Issue by nataliasayang** [freesewing/freesewing#2701] opened 2022-09-01 15:33 UTC
### What seems to be the problem? 🤔

When I generate a Teagan and select Expert mode > Show, then Design options > Advanced, the page goes blank.

I tried this in Chrome and Firefox. I tried with a couple different People in my account and some of the measurement presets. All had the same result.

### Design / Plugin / Package 🧐

designs/teagan

### Are you a FreeSewing patron? 😃

Yes, I am a tier-4 patron ❤️  💙

### Additional context

I'm not sure whether this is worth resolving in v2 as FreeSewing has shifted focus to v3. It's fine with me if this is closed without resolution.

**Comment by BenJamesBen** [comment] 2022-09-01 17:45
I am able to reproduce the problem on freesewing.org.

In lab.freesewing.dev, I note that there are 3 Advanced options with values as "No constant val yet" which is likely related to the issue. These Advanced options are inherited from Brian.
![Screen Shot 2022-09-01 at 10 38 48 AM](https://user-images.githubusercontent.com/109869956/187978714-aefd10ff-a350-452d-9e23-5bf3af7a3c8c.png)

**Comment by BenJamesBen** [comment] 2022-09-01 18:05
I note that the following change fixes the issue in the localhost version of the lab:
```diff
--- a/designs/teagan/config/index.js
+++ b/designs/teagan/config/index.js
@@ -37,9 +37,9 @@ const config = {
     bicepsEase: 0.05,
     shoulderEase: 0,
     collarEase: 0,
-    shoulderSlopeReduction: 0,
-    sleeveWidthGuarantee: 0.85,
-    frontArmholeDeeper: 0.005,
+    shoulderSlopeReduction: { pct: 0, min: 0, max: 80 },
+    sleeveWidthGuarantee: { pct: 85, min: 25, max: 100 },
+    frontArmholeDeeper: { pct: 0.005, min: 0, max: 0.5 },
```

However, I am not sure what was the design intent. Perhaps Teagan's designer intended for the values to be hard-coded and non-changeable? If so, then the fix would instead be to remove the 3 options from the Advanced menu.

**Comment by starfetch** [comment] 2023-01-23 17:47
Problem is still present on current (v2) website, but 'teagan' works fine [in the lab](https://lab.freesewing.dev/teagan).

**Comment by SeaZeeZee** [comment] 2023-04-10 14:51
This appears to be fixed in the v3 version of the lab but it's still an issue on lab.freesewing.dev. Is it worth redeploying the lab to check if that fixes things? Is this something that needs to be fixed in v2 or can we close the issue?

**Comment by BenJamesBen** [comment] 2023-04-18 05:09
I added an agenda item to the April 29 Contributor Call to ask if these sorts of bugs can/should be closed.

**Comment by BenJamesBen** [comment] 2023-05-11 14:33
Closing as Fixed in v3. (Won't be fixed in v2.)

**Closed by BenJamesBen** 2023-05-11 14:33 UTC
Labels: :bug: bug, :shirt: teagan, fixedInv3
