### ISSUE TITLE
[bug]: Undefined error for Charlie Chinos measurements

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#6894] opened 2024-06-19 18:50 UTC
Having saved my measurements as required for the Charlie Chinos design (https://freesewing.org/set?id=54701), when I attempt to create the design I am returned the errors below, and several screens of warnings, of which I am appending the first. It appears the parameters from the measurement set aren't being passed into the functions? Please let me know if this is a known issue, or is a workaround exists, as the concept is incredibly exciting if I can get it to work! 

[![User 83708](https://backend3.freesewing.org/users/83708/card)](https://next.freesewing.org/users/83708)

**Comment by IanLukeFinley** [comment] 2024-06-19 18:53
I'm not sure the error messages properly posted from the web submission portal, so adding here as well. 

![Screenshot 2024-06-19 144815](https://github.com/freesewing/freesewing/assets/107075390/c0e9bb4f-9dd1-4595-be8c-9b3420de16c0)

![Screenshot 2024-06-19 144815](https://github.com/freesewing/freesewing/assets/107075390/e866fbeb-9674-4796-b5be-0fe6383f007f)

**Comment by HaasJona** [comment] 2024-06-21 08:13
I'll look at this

**Comment by HaasJona** [comment] 2024-06-21 08:33
This is a duplicate of https://github.com/freesewing/freesewing/issues/6271. While the error handling can be improved in code, you can also work around this issue by using different measurements.

For example if you lower your seat measurements so that waist-to-seat is 10", the pattern will work okay. So I recommend to double check your measurements and follow these hints: https://freesewing.org/docs/about/faq/measurements-issues#seat-and-hips

Of course it's very possible that your measurements are correct and that the code needs to be improved.

@BenJamesBen as you were looking for a measurement set to debug the issue, this might be helpful.

**Comment by IanLukeFinley** [comment] 2024-06-21 16:35
Thank you for the feedback. 10" in that field does resolve the issue, so I'll go back through and double check all my measurements' accuracy. I appreciate your swift response!

**Comment by HaasJona** [comment] 2024-06-23 10:51
I'll close this issue as a duplicate. The pull request #6894 should fix this crash in the future and warn the user about their potentially incorrect measurements. However feel free to give us an update if you've verified that your measurements are indeed correct and you think the problem is in the pattern.

Thanks for the good bug report.

**Closed by HaasJona** 2024-06-23 10:51 UTC
Labels: :bug: bug, :robot: robot, needs-triage
