### ISSUE TITLE
[bug]: Wahid drafted for high bust

### ISSUE THREAD

**Issue by RockerKitten** [freesewing/freesewing#6118] opened 2024-02-21 21:58 UTC
### What seems to be the problem? 🤔

When Whaid is drafted for high bust, test shows that changing the chest measure changes nothing.
![image](https://github.com/freesewing/freesewing/assets/84648053/ac47dd57-7070-42b4-b6e6-7549c92fe392)
and doesn't show high bust as a measure to test. Chest appears to default to somewhere between hip and high bust.

### Design / Plugin / Package 🧐

designs/wahid

### Additional context
edit to add: my understanding of "draft for high bust" was that it would be drafted for high bust, then a FBA would be done as well to accommodate for the bust size, so this is either not working as intended, or my understanding is incorrect, which would imply that better/different documentation or wording is needed to clarify what exactly draft for high bust is intended to do given it's what's recommended for "those with breasts" 

_No response_

**Comment by BenJamesBen** [comment] 2024-02-23 04:06
- The behavior is not a bug. Wahid is behaving as intended. Draft for High Bust simply means that the High Bust measurement is used in place of the Chest measurement.
- The behavior of nothing changing when the Chest measurement is changed is normal and expected. This is because the Chest measurement is simply ignored when Draft for High Bust is enabled.
- Nothing in the Draft for High Bust option description suggests that a Full Bust Adjustment will be performed. So, there shouldn't be any reason why customers would think this.
- The option description appears to be accurate. The Draft for High Bust option does "result in a more fitted garment for people with breasts". That is, it produces a tighter garment.
- And, historically the option seems to have worked well for many people with breasts. So, the "Recommended for people with breasts." statement doesn't seem inappropriate.

But, if there are any changes or additions to the wording that might make things clearer or help customers, please provide the specific changes and wording you want to see.

The relevant messages are In `designs/brian/i18n/en.json`:
```json
    "draftForHighBust": {
      "t": "Draft for high bust",
      "d": "Draft the pattern for the high bust measurement (if available) rather than the (full) chest. This will result in a more fitted garment for people with breasts."
    },
    "draftForHighBustYes": {
      "t": "Draft using the high bust measurement",
      "d": "Drafts a pattern using the high bust measurements as the chest measurement. Recommended for people with breasts."
    },
    "draftForHighBustNo": {
      "t": "Draft using the chest measurement",
      "d": "Drafts a pattern using the chest measurement. Recommended for people without breasts."
    },
```

(The issue of optional measurements like `highBust` not showing up in the Test View is addressed by PR #6132.)

**Closed** 2024-03-02 14:37 UTC
Labels: :bug: bug
