### ISSUE TITLE
[bug]: Error when trying to edit a saved pattern for a deleted Person

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#4289] opened 2023-06-14 19:05 UTC
### What seems to be the problem? 🤔

Attempting to "Edit pattern" on a saved pattern made using measurements from a Person who has since been deleted results in an error: "This should never happen. Please report this."

This is on the current freesewing.org website. I was able to reproduce the issue:
![Screenshot 2023-06-14 at 11 47 50 AM](https://github.com/freesewing/freesewing/assets/109869956/f66e69b5-501c-4436-a557-a80439e4f49e)
![Screenshot 2023-06-14 at 11 48 02 AM](https://github.com/freesewing/freesewing/assets/109869956/d4e90064-ca41-4654-879d-119165003ba4)

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

I am filing this bug for tracking purposes. We will soon be switching to the v3 version of the freesewing.org website. Since we are rewriting almost all of the front end and backend code, it is likely that this bug will not exist in v3.

If this is the case, our agreed-upon process for this category of bug is to add the "fixed in v3" and "won't fix" labels and to close the bug.

**Comment by joostdecock** [comment] 2023-06-15 07:28
You can still resurrect this pattern. Go to where you got the error (editing the pattern). The in the menu click Recreate pattern.
You will need to pick a new person/set of measurements, and then the pattern will be recreated with all the same settings but the new measurements.
You can save the new pattern to your account, and remove the old one.

> *Since we are rewriting almost all of the front end and backend code, it is likely that this bug will not exist in v3.*

I guess we could handle the error better, but this is not a bug IMHO. Patterns are tied to the model. We do not store measurements along the pattern, but load them from the model. When the model disappears, there's no way for us to re-create the pattern.

The most safe fix would be that when somebody deletes a model, we delete all patterns that use that model.
That would allow us to wash our hands from this, but I think it's better to keep it since the pattern can still be recreated with different measurements.

**Comment by joostdecock** [comment] 2023-09-30 17:14
Not sure why I didn't close this earlier, but we are not backporting fixes to v2.

**Closed by joostdecock** 2023-09-30 17:14 UTC
Labels: :bug: bug
