### ISSUE TITLE
[bug]: Print Settings are not saved

### ISSUE THREAD

**Issue by PetrDobes** [freesewing/freesewing#5911] opened 2024-01-27 20:57 UTC
### What seems to be the problem? 🤔

I created a pattern from Brian body block and used A3 paper with Landscape page orientation to print it. I saved it using the "Save as new pattern" option. When I logged in again to my account and decided to update the pattern and print it again, I noticed that Print settings (both the page format and page layout) were back to default values (A4 and Portrait).

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment] 2024-01-28 04:29
I am able to reproduce the behavior described, but I believe that this is Not a Bug. Instead, I think that this is the intended behavior. 

By design, paper size is not part of a pattern, and it does not get saved to a pattern's settings. And, similarly it is also not part of a user account, and it does not get to a user's account settings. I think that the intent was that a user would want to print patterns on a variety of printers from day to day, so paper size wouldn't belong in either of those settings.

**Comment by joostdecock** [comment] 2024-02-04 17:26
As Ben explains, we (currently) consider these settings to be ephemeral. They are, in other words, not stored anywhere.

I feel that storing this would (further) blur the line between a pattern in FreeSewing, and a pattern as people who come to the site expect it based on their experience on other sites. Which basically means: a PDF file.

PDF files have page sizes. FreeSewing patterns do not. At least not until you export them.
So, while I do not think it makes sense to store this in a pattern, I do appreciate it is frustrating to constantly have to set your preferred page size.

I think the best way to tackle this would be to extend the account with a bunch of *defaults* which can include page size, but also other things that are up to personal preference (like SA on or off, or how wide to make it).

Give that this is a bug report, and we do not consider this a bug, I am going to close this, but I have opened #5958 to track this.

**Closed by joostdecock** 2024-02-04 17:26 UTC
Labels: :bug: bug
