### ISSUE TITLE
[bug]: Incorrect lab.freesewing.org URL in error report

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2675] opened 2022-08-28 13:21 UTC
### What seems to be the problem? 🤔

In the automated error report comment https://github.com/freesewing/freesewing/issues/2674#issuecomment-1229368533 , an URL is listed:
> Lab: 👉 https://lab.freesewing.org/v/next/unice?from=github&preload=44ce421b43486e6c26cf5e17b60ba02f

This URL uses the incorrect "lab.freesewing.org". It should be "lab.freesewing.dev" instead.

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

I do not understand how this error could have occurred. The source code in [sites/backend/src/controllers/github.js](https://github.com/freesewing/freesewing/blob/develop/sites/backend/src/controllers/github.js) clearly uses "lab.freesewing.dev".

**Comment by starfetch** [comment] 2023-04-23 22:19
> The source code in [sites/backend/src/controllers/github.js](https://github.com/freesewing/freesewing/blob/develop/sites/backend/src/controllers/github.js) clearly uses "lab.freesewing.dev".

This file was removed in 'refactor' commit https://github.com/freesewing/freesewing/commit/b45a1c61b4e0598b7932e527f4b16e24305a7341, therefore the issue is likely out of date. Closing for now, reopen of necessary,

**Closed by starfetch** 2023-04-23 22:19 UTC
