### ISSUE TITLE
[bug]: new design throws error after being created

### ISSUE THREAD

**Issue by anna-puk** [freesewing/freesewing#5207] opened 2023-10-18 17:10 UTC
### What seems to be the problem? 🤔

after running 'yarn new design', the files/folder are created and yarn lab runs, but the /designs/test3 page gives a server error

### Design / Plugin / Package 🧐

packages/new-design

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

see draft pull request to reproduce: https://github.com/freesewing/freesewing/pull/5201

**Comment by joostdecock** [comment] 2023-10-21 15:19
This should be fixed. Can you confirm @anna-puk ?

**Comment by anna-puk** [comment] 2023-10-21 20:02
> This should be fixed. Can you confirm @anna-puk ?

I no longer get the original error, but I do get a different one, which seems to be tied to `yarn reconfigure`. (See Discord for details.)

**Comment by joostdecock** [comment] 2023-10-22 09:27
```
Error [ERR_MODULE_NOT_FOUND]: 
  Cannot find module '/workspace/freesewing/node_modules/@freesewing/core-plugins/dist/index.mjs' 
  imported from /workspace/freesewing/packages/core/src/pattern/pattern-plugins.mjs
```

So, the file `packages/core/src/pattern/pattern-plugins.mjs` imports `@freesewing/core-plugins/dist/index.mjs`.
Because it loads from **dist**, that means it's loading the compiled (built) code.
The reason is that the core library does not import from source, but rather from `@freesewing/core-plugins` (the package) because of course that's the only way it can work outside our monorepo, which is where core is typically used.

Yarn has symlinked that folder to `plugins/core-plugins` so it will load form there. But the **dist** folder there will be empty until you've at least built it once. Because we don't keep build artifacts in the repository.

I have added `yarn buildall` to the `yarn kickstart` step, so this should no longer be an issue.
Confirmed by cloning a fresh copy of the repo, running `yarn kickstart` followed by `yarn new design` and finally `yarn lab`. 
![Screenshot 2023-10-22 at 11-26-39 Meh](https://github.com/freesewing/freesewing/assets/1708494/abb06b0f-1f02-4495-9916-323070177a97)
Works fine. Closing

**Closed by joostdecock** 2023-10-22 09:27 UTC
Labels: :bug: bug
