### ISSUE TITLE
Simon's sleeve placket cut [seems to be/is] too short

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1732] opened 2022-01-26 12:11 UTC
On Discord, `bumble` noticed that the slit in the Simon sleeve is not the correct length to slide in the placket:

![20220126_123808](https://user-images.githubusercontent.com/1708494/151160745-16237bc2-efa2-4253-bf60-926c72aed2e5.jpg)

That probably warrants a closer look.

**Comment by nicholasdower** [comment] 2022-01-26 16:27
I'm very excited to take a look at this one. Please let me know if you are already working on it.

**Comment by joostdecock** [comment] 2022-01-26 17:07
Nope, all yours.
I suspect it's related to the way the placket is folded which means it can't slide all the way to the top, and I probably forgot to take that into account.

**Comment by nicholasdower** [comment] 2022-01-26 17:56
Thinking I might be missing something...

Here is the overlap today:
![image](https://user-images.githubusercontent.com/9117775/151219347-013febdc-54c8-4381-bfa4-14092944d7c6.png)

And here is my understanding of the various points:
![image](https://user-images.githubusercontent.com/9117775/151218681-01f02e9c-1ee4-40a1-b589-d37dce1d3a51.png)

It seems to me that the cut should be aligned with the length. It also seems that the cut should end up being half the size of the overlap when it is folded. In reality it is a fraction of that size. 

The problem is that if all of this is true, then we don't need the zig or the zag:
![image](https://user-images.githubusercontent.com/9117775/151219288-572c8b6c-b8b9-44f8-b82c-f581d7074634.png)

I have tentatively sent this as a WIP PR here: https://github.com/freesewing/freesewing/pull/1735 but expect some changes will be required.

**Comment by nicholasdower** [comment] 2022-01-26 17:57
Oh, one more thing, the diagonal lines don't seem to line up with where the folds will be. Changed that too. Let's see...

**Comment by nicholasdower** [comment] 2022-01-26 19:02
In case this clarifies anything:
![image](https://user-images.githubusercontent.com/9117775/151229093-471148fc-f024-42db-b9f2-d58d3892a299.png)

**Comment by nicholasdower** [comment] 2022-01-26 21:01
Just checked some of my shirts (not made by me) and realized the cut is probably supposed to be less than half of the width so that the overlap completely covers and hides the underlap. Still haven't figured out what the zig and zag are for though. Will move the cut back to where it was.

**Comment by nicholasdower** [comment] 2022-01-26 21:18
Ah! The zig zag all makes sense now!

Here is the newest version:
![image](https://user-images.githubusercontent.com/9117775/151247957-89d2184a-c977-495a-a991-1aeb10d5aa50.png)

Will take another look in the morning to see if this still makes sense.

**Comment by nicholasdower** [comment] 2022-01-27 07:27
I still think the cut is awfully shallow. The actual size ends up being `width * 0.1 + 1.5`. For my sleeve placket that is 3.5 mm. The maximum it could be would be `width / 2` as that would result in the overlap and underlap sitting completely flush (no overhang). For my sleeveplacket that would be 10mm. Maybe instead of making the cut 35% of that it should instead be inverted to 65%.

Regardless, I think it would make sense to refactor the logic so that the cut size is explicit. I will do that next. There might be some other ways I can make it easier for future developers to modify this. Will take a look.

**Comment by joostdecock** [comment] 2022-01-27 08:02
I wish I could drop some authoritative answer on why this or why that, but I did that sleeve placket like, I dunno, 7 years ago or so.
So it's all kinda vague to me, but here's some of my thoughts:

![slpl](https://user-images.githubusercontent.com/1708494/151315018-dd7c2ddd-fbe4-4c91-8645-d367db3d19c6.png)

The green outline is the final form of the placket. The brownish lines are the outline of the fabric that's folder under (I did not include the pointy edge under-fold but you get the point.

- The length of the cut in the sleeve is determined by the bottom length of the (unfolded) placket. In other words, there where it goes upwards and then does the zig-zag. That edge is the edge that will 'bump' into the end of the cut in the sleeve. So this is the length that should match.
- That length should be greater than the vertical top-stitching line on the finalized placket. The only clearly visible green vertical line in the image above. The reason is that this will remain and unfinished edge, so it's important that it gets locked into the little 5-corner shape at the top of the placket.
- The zig-zag is not mandatory. All it does is strike a balance to have not too much fabric at the top (fiddly to fold that under those slanted angles) to having plenty of fabric at the base of our 5-corner thingie so that on the inside, we see more of the good side of the fabric (it's a better finish this way).
- The actual cut will lie more or less at the bottom of the zig-zag. So not in the middle of the placket, but rather between the (horizontal) brown dashed line and top green line

On a personal note, I find the more blunt tip of the placket more visually pleasing (in comparison to the sharper point you've created), although I'm certain your variety is easier to fold. There's no right or wrong when it comes to this, it's just preference.

**Comment by nicholasdower** [comment] 2022-01-27 08:27
Ah! Blunt tip. Ok that makes sense. I was trying to match the pattern to the instructions, which looked to me like a 45 degree angle:
![image](https://user-images.githubusercontent.com/9117775/151320461-2b4dfb0a-7f5e-4d2e-b03a-ba325685439d.png)

Now I think the instructions are just slightly simplified and that the blunt tip is a huge improvement. Especially since on my shirts you can see the folded bit sticking out a little.

I will revert the box change.

**Comment by nicholasdower** [comment] 2022-01-27 08:27
Regarding the zig zag, it makes sense that it removes bulk. Thanks!

**Comment by nicholasdower** [comment] 2022-01-27 08:34
>That length should be greater than the vertical top-stitching line on the finalized placket. The only clearly visible green vertical line in the image above. The reason is that this will remain and unfinished edge, so it's important that it gets locked into the little 5-corner shape at the top of the placket.

@joostdecock can you confirm that the cut should match the length of the placket as I have done in the PR? I understand that the vertical top stitch line needs to be to the left of the cut but in the pattern I believe the top-stitch line is drawn exactly at length. So maybe you are suggesting that I should move that line left a few mm. Does that sound right?

**Comment by joostdecock** [comment] 2022-01-27 09:29
@nicholasdower I'm on the road now, but I'll check the PR when I get home.

Meanwhile, yeah the end of the slit in the sleeve and thus were we turn inward towards the zig zag should lie (at least) a few millimeter beyond the vertical topstitch line, so that this topstitch locks it in place.

If you look at the very first picture you posted (current situation) that is the case.
So I'm cautiously optimistic that the only problem is the length at which we cut in, not the shape as such.

And as for the length being incorrect, perhaps it's as simple as having counted the seam allowance double or something

**Comment by nicholasdower** [comment] 2022-01-27 09:53
Thanks @joostdecock. I moved the box line. Here is the new vs the old as of now:
![image](https://user-images.githubusercontent.com/9117775/151335143-1ba158dd-c36f-48f9-bfb0-078fa6280991.png)

**Comment by joostdecock** [comment] 2022-01-27 09:56
Noice!

**Comment by nicholasdower** [comment] 2022-01-27 10:06
FYI I also made the change to make it clear how bit the cut will be (`width * 0.1 + 1.5`).

**Comment by joostdecock** [comment] 2022-01-27 10:26
Had a quick look at #1735 and I think we can merge this. Ok?

**Comment by nicholasdower** [comment] 2022-01-27 10:37
> Had a quick look at #1735 and I think we can merge this. Ok?

Merged. Marking this fixed.

**Comment by nicholasdower** [comment] 2022-01-27 10:37
As always, thanks for all the help!

**Closed by nicholasdower** 2022-01-27 10:37 UTC
Labels: :package: simon, :pause_button: blocks-release

**Comment by joostdecock** [comment] 2022-01-27 11:24
I did next to nothing. All credit to you.
