### ISSUE TITLE
[bug]: something is wrong with Jaeger/Bent's bicep calculations

### ISSUE THREAD

**Issue by lasermonkey12** [freesewing/freesewing#6607] opened 2024-04-23 03:21 UTC
### What seems to be the problem? 🤔

The generated sleeve gets larger if I reduce the bicep measurement, and changing bicep ease just changes the height of the armscye and doesn't actually affect the width of the sleeve at all.
My measurement set with the usual 13.25" bicep measurement gives 7.2" top sleeve width: [link](https://freesewing.org/new/jaeger#view=%22draft%22&settings=%7B%22measurements%22%3A%7B%22biceps%22%3A336.54999999999995%2C%22chest%22%3A958.8499999999999%2C%22hpsToBust%22%3A292.09999999999997%2C%22hpsToWaistBack%22%3A431.79999999999995%2C%22neck%22%3A368.29999999999995%2C%22shoulderToShoulder%22%3A406.4%2C%22shoulderSlope%22%3A22.5%2C%22waistToArmpit%22%3A209.54999999999998%2C%22waistToHips%22%3A107.94999999999999%2C%22hips%22%3A857.25%2C%22waist%22%3A800.0999999999999%2C%22shoulderToElbow%22%3A330.2%2C%22shoulderToWrist%22%3A558.8%2C%22wrist%22%3A171.45%2C%22highBust%22%3A901.6999999999999%7D%2C%22units%22%3A%22imperial%22%2C%22metadata%22%3A%7B%22setName%22%3A%22Laser%22%7D%2C%22expand%22%3Anull%2C%22paperless%22%3Atrue%2C%22options%22%3A%7B%7D%2C%22only%22%3A%5B%22jaeger.underSleeve%22%2C%22jaeger.topSleeve%22%5D%7D)
and that same measurement set with the bicep manually changed to 10" gives 8.28" top sleeve width: [link](https://freesewing.org/new/jaeger#view=%22draft%22&settings=%7B%22measurements%22%3A%7B%22biceps%22%3A254%2C%22chest%22%3A958.8499999999999%2C%22hpsToBust%22%3A292.09999999999997%2C%22hpsToWaistBack%22%3A431.79999999999995%2C%22neck%22%3A368.29999999999995%2C%22shoulderToShoulder%22%3A406.4%2C%22shoulderSlope%22%3A22.5%2C%22waistToArmpit%22%3A209.54999999999998%2C%22waistToHips%22%3A107.94999999999999%2C%22hips%22%3A857.25%2C%22waist%22%3A800.0999999999999%2C%22shoulderToElbow%22%3A330.2%2C%22shoulderToWrist%22%3A558.8%2C%22wrist%22%3A171.45%2C%22highBust%22%3A901.6999999999999%7D%2C%22units%22%3A%22imperial%22%2C%22metadata%22%3A%7B%22setName%22%3A%22Laser%22%7D%2C%22expand%22%3Anull%2C%22paperless%22%3Atrue%2C%22options%22%3A%7B%7D%2C%22only%22%3A%5B%22jaeger.underSleeve%22%2C%22jaeger.topSleeve%22%5D%7D)

**Comment by joostdecock** [comment] 2024-04-27 14:13
Closing as dupe of #6023

**Closed by joostdecock** 2024-04-27 14:13 UTC
Labels: :bug: bug
