### ISSUE TITLE
Investigate strangly deep armholes in Aaron

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1206] opened 2021-07-12 14:51 UTC
Daryl on Discord made a Teagan they're happy with, but is now having a weird result with Aaron where the armholes are enourmous.

- This Aaron is weird: https://gist.github.com/freesewing-bot/97d53a15d0cbda1d4a32581607caff19
- Yet this Brian looks ok: https://gist.github.com/freesewing-bot/eef70e3703fd898cdd3e6d89c9f36b14

:shrug:

**Comment by sannek** [comment] 2021-07-12 17:43
I'm looking into this (because I'm curious, but please lmk if you're already on it!). Not sure _how_ to fix it yet, but I'm pretty sure it happens because the chest and hip circumference are exactly the same. Adding even a mm to one of them, or changing the ease of one of them puts the armhole in the right place again.

Will report back when I figure out how to fix it.

**Comment by joostdecock** [comment] 2021-07-12 17:59
Thank you @sannek 🙏

I've assigned it to you so it's obvious this is being worked on, but no pressure 🤗

**Comment by sannek** [comment] 2021-07-12 18:27
Yeah ok, the issue is definitely floating point rounding nonsense... 

In this case because the two `x` coordinates arent _exactly_ the same you end up with a ridiculous slope that throws off the intersection calculation.

But how to deal with it is a bigger question I think... Should we round coordinates at a certain number of decimal points? Or have some kind of epsilon value within which we treat points are the same?

But on the other hand, this seems so rare and fairly easily worked around by tweaking literally any setting, so I don't know if it's worth the effort to add some rounding or whatever all across the board?

**Comment by sannek** [comment] 2021-07-14 08:25
Hm, looking at [this commit](https://github.com/freesewing/freesewing/commit/8924f2d40b9253e6930543277b4473b6cb5de937) it looks like rounding was removed just a few months ago 🙈

> Don't round coordinates internally to avoid path.split misses

That seems like a bigger problem than this one, so I guess there's not much we can do about this one without partially undoing that one?

My only suggestion would be to round to 2 or 3 decimals? Perhaps some kind of accuracy that is enough to cover the path splits, but small enough that it would fix tese `0.99999999997` kind of situations? If that's a good idea, @joostdecock  I can make a PR for that, otherwise I think we can close this issue.

**Comment by joostdecock** [comment] 2021-07-14 08:30
Yes rounding seemed like a good idea, so we added it. Then it turned out it was a bad idea so I removed it again :joy: 

Is there perhaps something specific we can do in Aaron? Like add a check for this? 
Where exactly in the code is this happening?

**Comment by sannek** [comment] 2021-07-14 09:42
What is happening is the following:
in `src/front.js:74` we calculate the underarm point by calculating the intersection with the original armhole and the hips at the specific `y` of the final armhole, 

But because the difference between `points.armhole.x` and `points.hips.x` is `0.0000000002` or something like that, the slope used to calculate the new `y` is HUGE and throws off the calculation.

Now looking at it again I think I do have a better specific suggestion, actually - thanks for rubber ducking 🦆 
Right now we calculate the armhole as follows:
```
  points.armhole = utils.beamIntersectsY(
    points.armhole,
    points.hips,
    points.armhole.y * (1 + options.armholeDrop)
  )
```
But it will be simpler _and_ fix the issue if we just do:
```
points.armhole = points.armhole.shiftFractionTowards(points.hips, options.armholeDrop);
```

I don't know if that is 100% exactly, perfectly the same result, but it sure _seems_ te same to me, so I can open a PR for that fix in a minute

**Comment by joostdecock** [comment] 2021-07-14 12:43
Commenting here rather than the PR because there's more context.

Basically, I'm concerned about the code we would replace:

```
  points.armhole = utils.beamIntersectsY(
    points.armhole,
    points.hips,
    points.armhole.y * (1 + options.armholeDrop)
  )
```

This should return a point that has a Y coordinate that is the Y-value of `points.armhole` from Brian, plus the `armholeDrop`.

If it doesn't do that, that's a bug in core that I feel we should fix.
Perhaps we could write a unit test that replicates this scenario and get it to fail?

I could have a look at it tonight, but sadly not sooner

**Comment by sannek** [comment] 2021-07-14 12:48
Yeah - good idea. I'll write a test and try to figure out _why exactly_ that floating point rounding creates weirdness there.

(Also tonight, because by now my lunch break is _definitely_ over)

**Comment by sannek** [comment] 2021-07-14 13:24
Ok couldn't let it go - but now I've pinpointed the issue I can get it out of my brain until I worry about how to fix it tonight: we're hitting a number overflow of some kind because when the difference between the two x-coordinates is almost zero, the slope approaches (negative) infinity (smaller than `Number.MIN_VALUE`, which sure seems problematic)

(I already thought it was very suspicious that the armhole was either at `y=0` or `y=512` with no other options)

To be continued...

**Closed** 2021-07-14 16:03 UTC
Labels: :package: aaron

**Comment by joostdecock** [comment] 2021-07-14 16:05
Closed this by checking for (almost) vertical lines in `utils.beamsIntersect()`
Check the linked commit for details.

**Comment by sannek** [comment] 2021-07-14 16:09
Perfect 💯 Beat me to it!
