### ISSUE TITLE
Bruce Pattern issue

### ISSUE THREAD

**Issue by blah-lah** [freesewing/freesewing#712] opened 2020-12-09 18:31 UTC
I’ve attached a picture of the error that came when I tried to get the pattern with My measurements. 
![782DFEDA-664E-4DA1-AAD4-B00A464EA779](https://user-images.githubusercontent.com/75751843/101671707-d8786500-3a22-11eb-8cee-d4ba2fb21cb0.jpeg)

**Comment by joostdecock** [comment] 2020-12-10 07:23
When this happens, there's a button to report the issue.
Please use that, as it will generate a crash report that allows us to recreate the issue.

Alternatively, if you can share your username on the site and the person you created this for, we can try to reproduce it that way.
Without more info, we cannot investigate this.

**Comment by blah-lah** [comment] 2020-12-10 15:40
Hello,

I hit the button, and it didn’t work. The link did however, and I had to
sign up to report the issue and that’s what I did. On git hub. My name on
hit hub is “Blah-ah” and My mans on freesewing is “SirJhaqLaMar” the person
I created this for is Myself based off My measurements. Named “JHA”

Thanks

**Comment by joostdecock** [comment] 2020-12-12 12:50
There is no user `SirJhaqLaMar`. Could you double-check the name please?

**Comment by blah-lah** [comment] 2020-12-12 13:59
Here is a pic of My profile. Where it says handle, I don’t know why this
random letters are there.

**Comment by joostdecock** [comment] 2021-02-07 14:43
Can't reproduce this without info from the user. Closing

**Closed by joostdecock** 2021-02-07 14:43 UTC
Labels: :thinking: needs-info
