### ISSUE TITLE
[bug]: (workbench) Cutonfold parts inherited from no-cutlist cutonfold parts are not mirroring properly

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3783] opened 2023-04-08 18:43 UTC
### What seems to be the problem? 🤔

If a new `cutonfold` part is inherited from an old `cutonfold` part that has no explicit cutlist, the new part is not mirrored properly. Two different, incorrect behaviors are seen depending on whether the new part has an explicit `cutonfold` macro or if it simply inherits the `cutonfold` from the old part.

However, the issue is not seen if the old part is given an explicit cutlist.

This issue when seen with Teagan.
![Screenshot 2023-04-08 at 9 57 52 AM](https://user-images.githubusercontent.com/109869956/230736860-ea500ff4-f942-4a53-a1f3-6d371df0d40f.png)
![Screenshot 2023-04-08 at 9 58 54 AM](https://user-images.githubusercontent.com/109869956/230736864-b0a5a422-f83f-4302-ac1d-65b42d162b11.png)

Again, the issue is not seen if the Front (old) part is given an explicit cutlist.
In `designs/teagan/src/front.mjs`:
```diff
@@ -162,2 +162,4 @@ function teaganFront({
 
+  store.cutlist.addCut({cut: 1})
+
   return part
```

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by eriese** [comment] 2023-04-10 16:50
this is caused by the same thing as issue as #3784, closing as a duplicate

**Closed by eriese** 2023-04-10 16:50 UTC
Labels: :bug: bug, :computer: lab
