### ISSUE TITLE
[bug]: creating a new design causes changes in unrelated files

### ISSUE THREAD

**Issue by anna-puk** [freesewing/freesewing#6265] opened 2024-03-02 21:14 UTC
### What seems to be the problem? 🤔

(This is a problem with the repository, not the website.)

Using `yarn new design` results in changes to all existing designs as well and updates to various dependencies. With the default GitPod settings, these files are not being ignored by git. They are therefore likely to end up in pull requests.

### Additional context

For my most recent pull request, @bobgeorgethe3rd helped me get rid of the superfluous files. This requires some experience / knowledge of what the various files do as well as multiple `git restore` commands (since the files are spread across multiple folders).

**Comment by joostdecock** [comment] 2024-03-03 11:01
We publish a stand-alone development environment for those who want an as-simple-as-possible experience.

You are using our monorepo, which is fine. But that also means you need to accept that you are operating in an environment that has a bunch of complexity.

For what it's worth, those _prebuild_ files that are being changed are kept in the repo to make it easier for people to work with our monorepo, as it requires less setup this way.

That being said, the purpose of our monorepo is not to make it easy for you to design patterns. That's what `@freesewing/new-design` is for.

Not a bug. Closing.

**Closed by joostdecock** 2024-03-03 11:01 UTC
Labels: :bug: bug
