### ISSUE TITLE
[bug]: "Recreate gist" flow leads to strange non-working state

### ISSUE THREAD

**Issue by gregsadetsky** [freesewing/freesewing#2614] opened 2022-08-19 21:32 UTC
### What seems to be the problem? 🤔

To reproduce:
- go to any design, say https://freesewing.org/designs/aaron/
- click the "New (design name) Pattern" button, bringing you to https://freesewing.org/create/aaron/
- click any of the preset sizes, say "M", bringing you to https://freesewing.org/create/aaron/for/size-40-a/
- click "Export pattern" on the left
- click the "Github Gist" button
- click the generated URL - in my case it was [this](https://gist.github.com/8bd3a29fcc9e43cc503b61c161dc247d).
- in the generated gist, click the hyperlink posted by freesewing-bot - in my case it was [this](https://freesewing.org/recreate/gist/8bd3a29fcc9e43cc503b61c161dc247d).
- the page on FreeSewing to which you'll be brought has problems (see screenshot below):
  - although the design "labels" (unsure of the right name) appear, the design "lines" (sorry again for incorrect terminology) are not there
  - the site's header seems incorrect/broken -- is the background image/color missing?
 
There are no errors in the Chrome DevTools, and the same problem happens when opening the page in an Incognito Window i.e. with no browser extensions.

![Screen Shot 2022-08-19 at 5 27 44 PM](https://user-images.githubusercontent.com/1017304/185709802-092777ef-7967-4746-a234-c398301fdfb8.png)

### Design / Plugin / Package 🧐

packages/core

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment] 2022-08-20 03:05
I am able to reproduce the bug. The problem seems to be with freesewing.org. The same gist recreates just fine in the workbench:
https://aaron.freesewing.dev/recreate/gist/8bd3a29fcc9e43cc503b61c161dc247d#draft

**Comment by BenJamesBen** [comment] 2022-08-20 14:15
The problem is that the pattern isn't _initially_ displayed properly on the Recreate Gist web page. The problem fixes itself once the web page re-displays the pattern.

Workaround 1:
1. Press the "moon/sun" icon in the web page header to toggle dark/light mode.
2. The pattern re-appears. The bug is not seen.

Workaround 2:
1. Browse to another web page via a link, for example by clicking on the "magnifying glass" icon in the web page header to go to the Search page.
2. Press the web browser "back" or "previous page" button to go back to the Recreate gist page.
3. The pattern appears normally. The bug is not seen.

**Comment by BenJamesBen** [comment] 2022-08-20 14:43
The issue seems to be that the CSS theme isn't applied to the page when it initially loads. Specifically, it is the \<div> element known as `#gatsby-focus-wrapper > div` or `//*[@id="gatsby-focus-wrapper"]/div`:

Upon initial page load:
`<div style="margin:0 auto;min-height:calc(100vh - 6rem);display:flex;flex-direction:column;justify-content:center;padding:1.5rem;width:calc(100% - 3rem)">`

After pressing the light/dark mode toggle:
`<div style="margin:0 auto;min-height:calc(100vh - 6rem);display:flex;flex-direction:column;justify-content:center;padding:1.5rem;width:calc(100% - 3rem)" class="theme-wrapper light desktop">`

After browsing to another page and using the "back" button:
`<div class="theme-wrapper light desktop">`

**Comment by BenJamesBen** [comment] 2022-08-20 15:17
The bug does not occur in a desktop browser window that is small/narrow. 

Upon initial page load, with a small browser window:
`<div style="margin:0 auto;min-height:calc(100vh - 6rem);display:flex;flex-direction:column;justify-content:center;padding:1.5rem;width:calc(100% - 3rem)" class="theme-wrapper light tablet">`

Something in the web server infrastructure (Gatsby?) is causing the initial Recreate Gist page to be incorrect in a normal-width desktop browser. Another thing that looks wrong on the problem page is that the header is not the full width of the browser window.

I suspect that the web server is incorrectly sending a web page intended for a mobile phone web browser and with the CSS theme missing.

**Comment by joostdecock** [comment] 2022-08-20 15:23
It's more tricky than the CSS not being applied. It's a so-called SSR problem, and those are easy to overlook because they never happen in the development environment.

So thanks for reporting this @gregsadetsky because it's easy to overlook.

The entire website is a React SPA (single page application). That means that the page loads the HTML from the server only on the initial load. All subsequent page loads are handled client-site with only the required new content loaded in the background, and then the page is updated by Javascript rather than fully reloaded.

The problem is the server-side HTML is generated at build-time. This is referred to as SSR (server-side render).
In this case, that HTML is broken because the page does a bad job of dealing missing GitHub gist reference (which is passed in the URL).
At build time, this page is build without a reference and so it should generate a placeholder page or loading indicator, abd then force a re-render in the client side.

It doesn't do that, so that's what needs to he fixed.

This only happens on the initial app bootstrap (a cold page load).
This is also why you can *fix it* by forcing a re-render of the page, like by navigating away and back, or by toggling dark mode.

The reason these are easy to miss is that there is no SSR in the development environment.

**Comment by joostdecock** [comment] 2023-09-30 17:59
Not backporting fixes to v2. Should be ok in v3. Closing (sorry)

**Closed by joostdecock** 2023-09-30 17:59 UTC

**Comment by gregsadetsky** [comment] 2023-09-30 18:22
no worries! thanks for following through

I tried to replicate the previously-found bug, and am seeing an issue on production right now -- I'll open a separate issue
