### ISSUE TITLE
New Jaeger jacket for Subaru - problem

### ISSUE THREAD

**Issue by SubaruParo** [freesewing/freesewing#732] opened 2020-12-19 14:35 UTC
Error: Called Path.shiftAlong(distance) with a distance of 2 but Path.length() is only 1.29

Error: Called Path.shiftAlong(distance) with a distance of 2 but Path.length() is only 1.29

Error: Unable to draft part bentBack

TypeError: Cannot read property 'x' of undefined
Error: Called Path.shiftAlong(distance) with a distance of 2 but Path.length() is only 1.29

Error: Called Path.shiftAlong(distance) with a distance of 2 but Path.length() is only 1.29

Error: Unable to draft part bentFront

TypeError: Cannot read property 'x' of undefined
Error: Called Path.shiftAlong(distance) with a distance of 2 but Path.length() is only 0.53

Error: Called Path.shiftAlong(distance) with a distance of 2 but Path.length() is only 0.53

Error: Unable to draft part front

TypeError: Cannot read property 'x' of undefined
Warning: One or more errors occured. Not packing pattern parts

**Comment by joostdecock** [comment] 2020-12-19 14:41
Can you generate a crash report on the website please (there's a button for that).
That will give us the info to reproduce this

**Comment by SubaruParo** [comment] 2020-12-19 14:57
Sorry, all I get when I click this button is a blank page

**Comment by joostdecock** [comment] 2020-12-19 15:00
Oh ok, that's not cool. I'll need to check that.

Ok, then please share your username on the site and the person you created the pattern for. That will allow me to reproduce it.

**Comment by SubaruParo** [comment] 2020-12-19 15:38
Thank you !
My username is: Natsuki
And the person I created it for is: Subaru

**Comment by joostdecock** [comment] 2020-12-19 17:01
I've created #733 for the error reporting not working. We should fix that since it's kinda important that people can report problems.

**Comment by joostdecock** [comment] 2020-12-19 17:55
Crash report at #734

**Comment by joostdecock** [comment] 2020-12-19 18:36
If you disable the seam allowance, the problem goes away.
Or rather, it will prevent the error, but the underlying issue is that the pattern is *weird* looking.

I had a quick look at your measurements, and I think it's worth double-checking them.

 - Your shoulder slope is 1.3 degrees, which almost certainly not correct
 - Your chest -> waist -> hips is 80 -> 99 -> 78 cm. This is not necessarily incorrect, but it does explain why the pattern is weirdly shaped. Unless you mis-measured, you have a waist that's significantly larger than chest-hips. That is not uncommon in men who tend to carry their weight in the abdominal region. However, the pattern tries to *fit( all those three areas, giving you a wonky effect. I think you'd be better off going for either of these two options:
    - Reduce your waist so it's more inline with your chest-hips. This will mean you won't be able to close your jacket, but it will hang more naturally, with your belly protruding out of it
    - Increase hips to the waist measurement, and your chest circumference to something like 90 or so. This way the jacket will be able to close, but it will be a bit large in chest/hips area

The sharp increase from chest to waist is also why the error occurs. Essentially, because of this, the side piece ends up being a pointy shape. When calculate the seam offset, what is supposed to be a curve is not essentially a point. As such, this throws an error.

For this reason, I am closing this. Since the solution here is not in the code, but to strike a compromise to find a jacket that fits you in the most flattering way.

Unless of course you mis-measured :)

**Closed by joostdecock** 2020-12-19 18:36 UTC
Labels: :package:jaeger, :thinking: needs-info

**Comment by SubaruParo** [comment] 2020-12-19 19:23
Alright, I will try those options, thank you for your time and work
